# Generated by Django 4.1.1 on 2022-10-13 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevportalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='User ID')),
                ('email_address', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Middle Name(s)')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Account Active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Account Admin')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Account Verified')),
            ],
            options={
                'verbose_name': 'Revportal User',
                'verbose_name_plural': 'Revportal Users',
            },
        ),
        migrations.CreateModel(
            name='RevportalUserAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_token', models.CharField(max_length=200, null=True, verbose_name='Verfication Token')),
                ('reset_password_token', models.CharField(max_length=200, null=True, verbose_name='Reset Password Token')),
                ('reset_instance_token', models.CharField(max_length=200, null=True, verbose_name='Reset Instance Token')),
                ('password_reset_at', models.DateTimeField(default='2001-01-01 00:00:00+00:00', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revportal User Authentication',
                'verbose_name_plural': 'Revportal Users Authentications',
            },
        ),
    ]
