# Generated by Django 4.1.1 on 2022-10-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revwand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revportaluser',
            old_name='is_admin',
            new_name='is_superuser',
        ),
    ]
