# Generated by Django 4.1.1 on 2022-10-13 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('revwand', '0002_rename_is_admin_revportaluser_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revportaluserauthentication',
            options={'verbose_name': 'Revportal User Authentication', 'verbose_name_plural': 'Revportal Users Authentication'},
        ),
        migrations.AddField(
            model_name='revportaluser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='revportaluser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='revportaluserauthentication',
            name='password_reset_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='revportaluserauthentication',
            name='reset_instance_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Reset Instance Token'),
        ),
        migrations.AlterField(
            model_name='revportaluserauthentication',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Reset Password Token'),
        ),
        migrations.AlterField(
            model_name='revportaluserauthentication',
            name='verification_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Verfication Token'),
        ),
    ]
