# Generated by Django 4.1.1 on 2022-10-13 12:15

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('revwand', '0003_alter_revportaluserauthentication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revportaluser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revportaluser',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 13, 12, 15, 4, 340686, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
